### ISSUE TITLE
Error getting valid response from api.

### ISSUE THREAD

**Issue by daniloparrajr** [AuthorizeNet/sample-code-php#109] opened 2018-03-23 06:56 UTC
Sample code doesn't seem to work. I have the sample code cloned and have composer update with no errors. But when I try to run the sample code it gives me 'Error getting valid response from api'
![api-error](https://user-images.githubusercontent.com/25006926/37815575-5b4eb7b8-2eaa-11e8-95fa-6cf806f3bd8a.png)

**Comment by ashtru** [comment] 2018-03-24 21:52
Thanks for raising the issue, @danyaneh and apologies for the inconvenience.

This issue was caused by change in the certificate used for verification by the API endpoint. You can replace the .../lib/ssl/cert.pem with the latest [cert.pem](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/ssl/cert.pem).

This issue has been fixed in latest release of the SDK (version [ 1.9.6](https://github.com/AuthorizeNet/sdk-php/tree/)) . Upgrading to it will also resolve the issue.


_Join the [Authorize.Net developer forum](https://community.developer.authorize.net/) to keep abreast with latest features and contribute ideas.
Thanks
Ashutosh_

**Comment by danyaneh** [comment] 2018-03-26 01:50
Thanks @ashtru, have the SDK updated to 1.9.6 and its working now.

**Comment by prthatip123** [comment] 2018-12-17 08:33
Hi ashtru i am getting the issue suddenly Uncaught exception 'Exception' with message 'Error getting valid response from api.
can you please suggest what changes i have to do it.

**Comment by ashtru** [comment] 2018-12-17 09:54
Can you check your `phplog` file for this request?
Are you able to confirm your network connectivity to the API endpoint?

**Comment by prthatip123** [comment] 2018-12-17 09:58
Hi ashtru 
CURL ERROR: Could not resolve host: apitest.authorize.net

**Comment by gnongsie** [comment] 2018-12-17 10:07
Hi @prthatip123 ,

We have checked the SDK and we are not seeing any issues. 

Can you give us the steps to reproduce this issue? Any particular API call which is failing?

**Comment by prthatip123** [comment] 2018-12-17 10:12
Hi Gabriel

Till yesterday it was working but from today morning my sdk-php is not responding 

I have not done any changes.

**Comment by kikmak42** [comment] 2018-12-17 10:15
> Hi ashtru
> CURL ERROR: Could not resolve host: apitest.authorize.net

Hi @prthatip123, can you check if https://apitest.authorize.net/xml/v1/request.api is accessible from you machine. It seems from your error you are having a network connection issue (which may happen if your firewall configuration changed or internet provider changed something, maybe different proxy server).

**Comment by ashtru** [comment] 2018-12-17 11:12
Hi @prthatip123 , you can check the output of curl command in the shell/command prompt:
$ `curl  "https://apitest.authorize.net/xml/v1/request.api"`

Non-zero bytes should be returned and the output must be `{"messages":{"resultCode":"Error","message":[{"code":"E00003","text":"Root element is missing."}]}}`

As @kikmak42 stated, something related to your network might have changed. Or some times, even restarting the server could resolve your issue. Ref: https://stackoverflow.com/questions/1341644/curl-and-https-cannot-resolve-host

**Comment by prthatip123** [comment] 2018-12-17 13:09
https://apitest.authorize.net/xml/v1/request.api   i run this url in my machine through browser.
i am getting the below output.
{"messages":{"resultCode":"Error","message":[{"code":"E00003","text":"Root element is missing."}]}}

As you have suggested to restart my machine so i have restarted my machine.

but still my issue did not get resolved. please can you help me to resolve the issue.

why my  api suddenly not working.

**Comment by prthatip123** [comment] 2018-12-21 08:51
sdk-php is working fine. Thanks

**Comment by gnongsie** [comment] 2018-12-21 09:14
Closing this issue based on the comment above.

**Closed by gnongsie** 2018-12-21 09:14 UTC
